var a=!0,f=!1,g={c:{}};g.c.g=function(b){b=b.split(".");for(var c=window,d=0;d<b.length;d++)"undefined"==typeof c[b[d]]&&(c[b[d]]={}),c=c[b[d]]};g.c.Ia=function(b,c){var d;for(d=0;d<b.length;d++)if(b[d]==c)return a;return f};g.c.w=function(b){if(b)for(;" "==b.charAt(0);)b=b.substr(1);return b};g.c.g("shell.lib");g.c.get=function(b){b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");b=RegExp("[\\?&]"+b+"=([^&#]*)").exec(window.location.href);return null==b?"":decodeURIComponent(b[1]).replace(/\+/g," ")};
g.c.g("shell.lib.cookie");g.c.cookie.list={};g.c.cookie.t=function(b,c){for(var d=b.split(";"),e=0;e<d.length;e++){var h=d[e].split("="),j=g.c.w(h[0]),h=g.c.w(h[1]);c&&g.c.cookie.list[j]!=h&&g.c.cookie.set(j,h,365);g.c.cookie.list[j]=h}};g.c.cookie.get=function(b){return g.c.cookie.list[b]};
g.c.cookie.set=function(b,c,d){var e=new Date;e.setTime(e.getTime()+864E5*d);document.cookie=b+"="+c+"; expires="+e.toGMTString();"guest"!=g.d.v&&"loggedin"!=b&&(e="",0>d&&(e="&del=1"),g.e.G("http://goosh.appspot.com/cookie?key="+encodeURIComponent(b)+"&val="+encodeURIComponent(c)+"&callback=shell.lib.cookie.fetch"+e,a));return g.c.cookie.list[b]=c};g.c.cookie.pa=function(b){g.c.cookie.set(b,"",-100);g.c.cookie.list[b]=null};g.c.cookie.O=function(){return g.c.cookie.list};g.c.g("shell.lang");
g.lang.list={ca:"ar",ea:"bg",fa:"ca",ga:"zh",ha:"zh-cn",ia:"zh-tw",ma:"hr",na:"cs",oa:"da",ra:"nl",sa:"en",ta:"et",va:"tl",wa:"fi",xa:"fr",ya:"de",Aa:"el",Ca:"iw",Fa:"hi",Ha:"hu",Ja:"id",Ka:"it",La:"ja",Ma:"ko",Na:"lv",Qa:"lt",Ta:"no",Wa:"fa",Xa:"pl",Ya:"pt",$a:"ro",ab:"ru",bb:"sr",eb:"sk",fb:"sl",gb:"es",hb:"sv",ib:"th",jb:"tr",kb:"uk",nb:"vi"};g.lang.reverse={};for(key in g.lang.list)g.lang.reverse[g.lang.list[key]]=key;g.c.g("shell.gui");g.a.r=f;g.a.u=f;g.a.D=f;g.a.i=f;g.a.j=f;g.a.N=function(b){return document.getElementById(b)};
g.a.S=function(){g.a.r=document.getElementById("input");g.a.u=document.getElementById("output");g.a.D=document.getElementById("prompt");g.a.i=document.getElementById("inputfield");g.a.j=document.getElementById("body");g.a.i.createTextRange?(g.a.i.onkeyup=new Function("return shell.keyboard.mcursor(event);"),g.a.j.onfocus=new Function("return shell.gui.focusinput(event);"),g.a.j.onclick=new Function("return shell.gui.focusinput(event);"),g.a.j.onkeydown=new Function("return shell.keyboard.keyDownHandler(event);")):
(g.a.i.onkeyup=g.b.V,g.a.j.onfocus=g.a.q,g.a.j.onclick=g.a.q,g.a.j.onkeydown=g.b.T)};g.a.error=function(b){g.e.Z();g.a.C("Error: "+b+"<br/> <br/>");g.a.H();g.a.q();g.a.scroll()};g.a.l=function(b){g.a.C(b+"<br/>")};g.a.C=function(b){var c=document.createElement("div");c.innerHTML=b;g.a.u.appendChild(c)};g.a.Oa=function(){return"<span class='less'>If you use the noscript firefox-extension, add \"ajax.googleapis.com\" to the whitelist.</span>"};g.a.info=function(b){return"<span class='info'>"+b+"</span>"};
g.a.clear=function(){g.a.u.innerHTML=""};g.a.H=function(){g.a.r.style.display="block"};g.a.R=function(){g.a.r.style.display="none"};g.a.q=function(){var b="";document.selection?b=document.selection.createRange().text:window.getSelection&&(b=window.getSelection().toString());0==b.length&&(document.z.F.value=document.z.F.value,"none"!=g.a.r.style.display&&document.z.F.focus())};g.a.lb=function(){g.a.prompt=g.d.v+"@"+g.d.host+":80/"+g.d.mode+g.d.X;g.a.D.innerHTML=g.a.prompt};
g.a.scroll=function(){window.scrollBy(0,122500)};g.a.s=function(b,c,d){try{return g.a.N(b).style[c]=d,a}catch(e){return f}};g.a.o=function(b,c){var d=document.createElement("div");d.innerHTML="<br style='line-height:0px;'/><style>"+b+" {"+c+"}</style>";g.a.j.appendChild(d)};g.c.g("shell.set");
g.set.f=function(b,c,d,e,h){this.name=b;this.K=d;this.L=c;h?this.max=h:this.max=2E3;e?this.min=e:this.min=0;e&&h&&(this.K+=" ("+e+".."+h+")");this.get=function(){return eval(""+this.name+";")};this.set=function(b){b>=this.min&&b<=this.max&&eval(""+this.name+" = '"+b+"';");return a}};g.set.list={};g.set.list.lang=new g.set.f("shell.config.lang","en","google default language");
g.set.list.lang.set=function(b){if(g.lang.reverse[b])g.d.lang=b;else if(g.lang.list[b])g.d.lang=g.lang.list[b];else return f;return a};g.set.list.Y=new g.set.f("shell.config.numres","4","number of results for google-searches",1,100);g.set.list.timeout=new g.set.f("shell.config.timeout","4","timeout for ajax requests in seconds",1,100);g.set.list["style.bg"]=new g.set.f("shell.config.bgcolor","#000000","shell background color");
g.set.list["style.bg"].set=function(b){return g.a.s("body","backgroundColor",b)&&g.a.s("inputfield","backgroundColor",b)?(g.d.da=b,a):f};g.set.list["style.fg"]=new g.set.f("shell.config.fgcolor","#ffffff","shell font color");g.set.list["style.fg"].set=function(b){return g.a.s("body","color",b)&&g.a.s("inputfield","color",b)?(g.d.ua=b,a):f};g.set.list["style.hl"]=new g.set.f("shell.config.hlcolor","#009900","shell highlight color");
g.set.list["style.hl"].set=function(b){g.a.o(".info","color: "+b);g.a.o("a:visited.info","color: "+b);g.d.Ga=b;return a};g.set.list["style.sh"]=new g.set.f("shell.config.shcolor","#ffffff","shell 'shaded' color");g.set.list["style.sh"].set=function(b){g.a.o(".less","color: "+b);g.d.cb=b;return a};g.set.list["style.link"]=new g.set.f("shell.config.linkcolor","#ffffff","shell link color");g.set.list["style.link"].set=function(b){g.a.o("a","color: "+b);g.d.Pa=b;return a};
g.set.list["style.vlink"]=new g.set.f("shell.config.vlinkcolor","#ffffff","shell visited link color");g.set.list["style.vlink"].set=function(b){g.a.o("a:visited","color: "+b);g.d.ob=b;return a};g.set.list["place.width"]=new g.set.f("shell.config.mapwidth","300","width of map image",20,600);g.set.list["place.height"]=new g.set.f("shell.config.mapheight","150","height of map image",20,500);
g.set.S=function(b,c){if("guest"!=g.d.v)if(b)g.e.B(b)&&(g.a.l("Loading remote settings..."),g.c.cookie.t(document.cookie),g.c.cookie.t(c,a));else{g.e.G("http://goosh.appspot.com/cookie?callback=shell.set.init");return}else g.a.l("Loading local settings..."),g.c.cookie.t(document.cookie);var d=g.c.cookie.O();for(key in g.set.list){var e=f;d[key]&&(e=d[key]);e&&g.set.list[key].set(e)?g.a.l("&nbsp;"+key+" => &quot;"+e+"&quot;."):g.set.list[key].set(g.set.list[key].L)}g.a.l("");g.za()};g.c.g("shell.ajax");
g.e.n=[];g.e.U=f;g.e.Z=function(){for(key in g.e.n)g.e.B(key)};g.e.qa=function(b){g.a.l("Error: Operation timed out. "+b);document.all||g.a.l("<span class='less'>If you use the noscript firefox-extension, add \"ajax.googleapis.com\" to the whitelist.</span>");g.a.l("");g.e.n[b]=f;(b=document.getElementById(b))&&document.body.removeChild(b);g.a.H();g.a.q();g.a.scroll();document.all||stop()};
g.e.B=function(b){return g.e.n[b]?(clearTimeout(g.e.n[b]),g.e.n[b]=f,(b=document.getElementById(b))&&document.body.removeChild(b),a):f};g.e.P=function(){var b=(new Date).getTime();g.e.n[b]=setTimeout("shell.ajax.deletecontext('"+b+"');",1E3*g.d.timeout);return b};g.e.G=function(b,c){var d="none";c||(d=g.e.P(),g.e.U=d,g.a.R());var e=document.createElement("script");document.body.appendChild(e);e.src=b+"&context="+d+"&";e.id=d};g.c.g("shell.config");g.d.ba="ABQIAAAA0cXSEVCNSwf_x74KTtPJMRQP4Q7D8MPck7bhT7upyfJTzVDU2BRxkUdd2AvzlDDF7DNUJI_Y4eB6Ug";
g.d.v="user";g.d.host="iiitbh-acm.org";g.d.mode="";g.d.X="$&nbsp;";g.d.Ua=4;g.d.timeout=4;g.d.start=0;g.d.Sa;g.d.lang="en";g.d.mb=[];g.d.ja=[];g.d.ka=[];g.c.g("shell.keyboard");g.b.p=[];g.b.m=1;g.b.J="";g.b.k=[];g.b.h=0;g.b.A=0;g.b.I=function(b){g.b.m>g.b.p[b].length&&(g.b.m=1);g.b.p[b][g.b.m]&&(g.a.i.value=g.b.p[b][g.b.m]);var c=g.a.i;c.createTextRange?(c=c.createTextRange(),c.moveStart("character",b.length),c.select()):c.setSelectionRange&&c.setSelectionRange(b.length,c.value.length)};
g.b.M=function(){this.$=function(b,c,d){g.b.p[c]=d;g.b.I(c);return a}};window.Q=[];window.Q.aa=new g.b.M;g.b.T=function(b){!b&&window.event&&(b=window.event);b&&(_lastKeyCode=b.keyCode);if(b&&9==b.keyCode){b.cancelBubble=a;b.returnValue=f;b=g.b.J;if(""!=b)if(g.b.p[b])g.b.m+=2,g.b.I(b);else{g.b.m=1;var c=document.createElement("script");document.body.appendChild(c);c.src="http://www.google.com/complete/search?hl="+g.d.lang+"&js=true&qu="+encodeURIComponent(b)}return f}};
g.b.V=function(b){b=b.keyCode;if(0<g.b.k.length){if(38==b||40==b)g.b.k[g.b.h]?g.b.k[g.b.h]=g.a.i.value:g.b.A=g.a.i.value;38==b?(g.b.h--,0>g.b.h&&(g.b.h=0)):40==b&&(g.b.h++,g.b.h>g.b.k.length&&(g.b.h=g.b.k.length));if(38==b||40==b)g.a.i.value=g.b.k[g.b.h]?g.b.k[g.b.h]:g.b.A}9!=b&&13!=b&&(g.b.J=g.a.i.value);13==b&&g.la()};g.c.g("shell.modules");g.c.g("shell.module");g.c.g("shell.modobj");g.W.list=[];g.Ra.f=function(){this.mode=f;this.Va="";this.Da="no helptext yet.";this.Ea="";this.Ba=f;this.Y=[]};
g.W.Za=function(b,c){c||(c="base");eval("shell.module."+b+".prototype = new shell.module."+c+";shell.modobj."+b+" = new shell.module."+b+';shell.modules.list["'+b+'"] = shell.modobj.'+b+";")};

